### ISSUE TITLE
Version 1.2.2 Breaks The Ability To Go to The Company Building

### ISSUE THREAD

**Issue by FlowtacKendall** [IAmBatby/LethalLevelLoader#83] opened 2024-04-29 00:28 UTC
Hey there,

So the most recent version LethalLevelLoader at the time of this post, Version 1.2.2, breaks the ability to go to The Company Building, as stated in the header/title.  When we reach the end of our 3 day quota and its time to sell our scrap, we go to the terminal to type in The Company Building in order to route the ship there, or go to Moons & then type The Company Building, but it doesn't register at all when we hit enter.  The text we type in "The Company Building" stays at the bottom of the screen and is able to be backspaced away, etc, as if we never hit Enter.  So, we began to troubleshoot through our mods and eventually got to the point where we narrowed it down to just having LethalLevelLoader & its dependencies enabled.  The problem persisted.  We disabled LethalLevelLoader 1.2.2 and suddenly we are able to route to the Company Building without any issue.  We re-enabled all of our mods except for LethalLevelLoader 1.2.2, and we're still able to route to The Company Building properly.

No idea what was changed in Version 1.2.2 to cause this issue, but it's definitely a major issue if we can't route to The Company Building at all.

**Comment by Retr0sec7** [comment] 2024-04-29 05:17
Same is happening to me. I'm using LethalLevelLoaderFixedV50 which fixes the issue, but for some reason it was labeled as deprecated

**Comment by dog199200** [comment] 2024-04-29 09:13
Same here: Came to report this issue

**Comment by chibranche** [comment] 2024-04-29 10:09
Same on my side, reverting to 1.2.1 seems to correct the issue

**Comment by 1410677474** [comment] 2024-04-29 10:51
You can use AutoCompanyBuilding to resolve this

**Comment by Xentax5** [comment] 2024-04-29 12:46
I have the same problem. Version 1.2.1 worked fine.

**Comment by Xentax5** [comment] 2024-04-29 12:58
> You can use AutoCompanyBuilding to resolve this

Thanks for this temporary fix! :D

**Comment by Jawbeast** [comment] 2024-04-29 21:20
Same problem here, even with only LLL and it's dependecies

**Comment by joelou1** [comment] 2024-04-30 02:17
Here's more information comming from BepInEx

`[Info   : Unity Log] Parsed word: com
[Info   : Unity Log] noun keyword: company ; verb keyword: route ; result null? : False
[Info   : Unity Log] result: CompanyMoonroute
[Error  : Unity Log] IndexOutOfRangeException: Index was outside the bounds of the array.
Stack trace:
LethalLevelLoader.TerminalManager.LockedNodeEventTest (TerminalNode& currentNode, TerminalNode& loadNode) (at <bed140a3e66641339c3af806fdbbd3ed>:IL_0006)
LethalLevelLoader.TerminalManager.OnBeforeLoadNewNode (TerminalNode& node) (at <bed140a3e66641339c3af806fdbbd3ed>:IL_004D)
LethalLevelLoader.Patches.TerminalLoadNewNode_Prefix (Terminal __instance, TerminalNode& node) (at <bed140a3e66641339c3af806fdbbd3ed>:IL_001B)
(wrapper dynamic-method) Terminal.DMD<Terminal::LoadNewNode>(Terminal,TerminalNode)
Terminal.OnSubmit () (at <255c0877f9414c3aa6f1fe5079ac13f3>:IL_00FB)
UnityEngine.Events.InvokableCall.Invoke () (at <e27997765c1848b09d8073e5d642717a>:IL_0010)
UnityEngine.Events.UnityEvent`1[T0].Invoke (T0 arg0) (at <e27997765c1848b09d8073e5d642717a>:IL_0049)
TMPro.TMP_InputField.SendOnEndEdit () (at <9baa8119dbcd498f902c1a92f10843c1>:IL_000E)
TMPro.TMP_InputField.ReleaseSelection () (at <9baa8119dbcd498f902c1a92f10843c1>:IL_001B)
TMPro.TMP_InputField.DeactivateInputField (System.Boolean clearSelection) (at <9baa8119dbcd498f902c1a92f10843c1>:IL_00B0)
TMPro.TMP_InputField.OnUpdateSelected (UnityEngine.EventSystems.BaseEventData eventData) (at <9baa8119dbcd498f902c1a92f10843c1>:IL_007C)
UnityEngine.EventSystems.ExecuteEvents.Execute (UnityEngine.EventSystems.IUpdateSelectedHandler handler, UnityEngine.EventSystems.BaseEventData eventData) (at <17de86d66286445fa95af59fa8fa644d>:IL_0000)
UnityEngine.EventSystems.ExecuteEvents.Execute[T] (UnityEngine.GameObject target, UnityEngine.EventSystems.BaseEventData eventData, UnityEngine.EventSystems.ExecuteEvents+EventFunction`1[T1] functor) (at <17de86d66286445fa95af59fa8fa644d>:IL_0067)
UnityEngine.EventSystems.EventSystem:Update()`

**Comment by tocram1** [comment] 2024-04-30 15:45
(duplicate of #77)

**Comment by IAmBatby** [comment] 2024-06-27 03:18
Resolved in future versions of the project.

**Closed by IAmBatby** 2024-06-27 03:18 UTC
