### ISSUE TITLE
Ship doesn't leave with latest version

### ISSUE THREAD

**Issue by Doxhot** [IAmBatby/LethalLevelLoader#104] opened 2024-05-17 02:45 UTC
1.2.3 breaks the ability for the ship to leave the company moon. The lever flips and says the ship is in motion but the ship does not move

**Comment by EfJun1** [comment] 2024-05-17 03:52
(duplicate of https://github.com/IAmBatby/LethalLevelLoader/issues/100)

**Comment by IAmBatby** [comment] 2024-06-27 03:38
Resolved in future versions of the project.

**Closed by IAmBatby** 2024-06-27 03:38 UTC
