### ISSUE TITLE
[v49] Conflict with LethalLevelLoader

### ISSUE THREAD

**Issue by utterlynowhere** [IAmBatby/LethalLevelLoader#7] opened 2024-01-16 19:57 UTC
Was asked by Uncertain Company's author to leave the issue here too.

Weather shows up regardless if the setting HideWeather is true or not.

Tested only with LethalLevelLoaders and its dependencies alongside Uncertain Company. 

Attached is a log below. Test for log is as follows:

1. Start game.
2. Route planet.
3. Start ship.
4. Return to orbit.
5. Route to another planet.
6. Start ship.
7. Return to orbit.

https://pastebin.com/sS5JfQxB

**Comment by Hardeh** [comment] 2024-01-19 01:36
I'd like to see it fixed as well, we can't play with hidden weather while LLL is active and it's sad

**Comment by DHStyle541** [comment] 2024-01-23 07:59
Please fix we need Uncertain Company. because Hide Weather is best :))

**Comment by IAmBatby** [comment] 2024-01-26 23:20
Resolved in the upcoming update, Thank you for your report and apologies for the inconvenience. Will close this when it's confirmed to be resolved after the release.

**Comment by IAmBatby** [comment] 2024-06-27 03:10
Resolved in future versions of the project.

**Closed by IAmBatby** 2024-06-27 03:10 UTC
